### ISSUE TITLE
Slight tweak recommended for restriction on autoupdating code

### ISSUE THREAD

**Issue by RonSpawnson** [TagproMLTP/TagproScriptsWhitelist#16]
After discussing with Ashmungashma we realized the following: 

In case a dev wants to retain autoupdating code, it should be permissible to use the updateurl annotation provided the url specified points to the **whitelist url of the userscript** rather than an externally hosted version. This would mean that the userscript will be able to update automatically, but **only after the whitelist officially approves of and pushes the update**.

Therefore, I'd recommend the use of updateurl be allowed, but only if the url points to **the official whitelisted script**.

**Comment by hunnefeldtyler** [comment]
Agreed! I'll change the ones in the whitelist tonight when I get the rest posted
